services:
  - type: web
    name: smartbank-dashboard
    runtime: python
    plan: free
    branch: main

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: APP_NAME
        value: SmartBank

    healthCheckPath: /
